config/routes.rb
Pipeline::Application.routes.draw do
  resources :jobs do
    resources :runs
    match 'files' => 'files#index'
    match 'download' => 'jobs#download'
  end
  match 'jobs/:id/start' => 'jobs#start_job', :as => :start_job
  match 'jobs/:job_id/runs/:id/stop' => 'runs#stop', :as => :stop_run
  match 'jobs/:job_id/runs/:id/restart' => 'runs#restart', :as => :restart_run

  resources :commands do
    member do
      match 'download' => 'commands#download'
    end
  end
  

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "users#index"

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  belongs_to :user
  has_many :runs, :dependent => :destroy
  after_create :create_folder 
  # DEPRECATION WARNING: Base#after_create has been deprecated, please use Base.after_create :method instead. (called from <class:Job> at /Users/cgenco/Dropbox/School_11-12/UTSW/pipeline/app/models/job.rb:7)
  def create_folder
    Dir.mkdir path
  end
  
  def status
    
  end
  
  def running?
    self.runs.each{|run| return true if run.running?}
    false
  end
  
  def finished?
    self.runs.inject(true){|tf, run| run.finished? && tf}
  end
  
  def path
    dirname = "#{id}_#{name.gsub(' ','_').underscore}"
    JOB_FILES_PATH.join(dirname)
  end
  
  def nested_run_ids
    flat_runs = self.runs.map{|run| {:id => run.id, :parent_id => run.waiting_on_run_id}}
    tree = make_tree(flat_runs)
  end
  
  private
  
  def make_tree(array, parent_id = nil)
    children = []
    array.each{|e| children << e[:id] if e[:parent_id] == parent_id}
    array.delete_if{|e| e[:parent_id] == parent_id}
    
    children.map{|child| [child, make_tree(array, child)]}
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :daemon_running?
  
  def index
    @jobs = Job.all.reverse
  end

  def show
    @job = Job.find(params[:id])
    @runs = @job.runs
    @nested_run_ids = @job.nested_run_ids
    
    respond_to do |format|
       format.html
       format.zip #{render :data => Zippy.new('foo.txt' => 'bar').data}
     end
  end
      
  def download
    file_name = "pictures.zip"
    t = Tempfile.new("my-temp-filename-#{Time.now}")
    Zip::ZipOutputStream.open(t.path) do |z|
      runs.each do |run|
        title = run.command.alias + ".xml"
        z.put_next_entry(title)
        z.print run.xml
      end
    end
    send_file t.path, :type => 'application/zip', :disposition => 'attachment', :filename => file_name
    t.close
  end
  
  def start_job
    @job = Job.find(params[:id])
    @job.runs.each{|run|
      # don't start a run that's finished; those runs need to be reset first
      if !run.finished? && run.waiting_on_run_id == nil
        run.start
      end
      
      # supports adding a command to a completed run
      if !run.finished? && run.waiting_on_run && run.waiting_on_run.finished?
        run.start
      end
    }
    
    redirect_to @job, :notice => 'Started'
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      redirect_to @job, :notice => "Successfully created job."
    else
      render :action => 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to @job, :notice  => "Successfully updated job."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url, :notice => "Successfully destroyed job."
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit 'Save', :class => 'submit'

app/views/jobs/_run.html.haml
%li
	%h2{:class => run.torque_status}
		=run.command.name
		%span.status
			-unless run.torque_status.nil?
				=run.status
			-else
				press "start" to start this run
		%span.torque_job_id{:style => 'display:none'}=run.torque_job_id if run.torque_job_id
		%span.info
			="runtime: " + distance_of_time_in_words(run.started_at, run.ended_at ? run.ended_at : Time.now) if run.started_at
			=link_to "stop", stop_run_path(@job.id, run.id), {:confirm => 'Are you sure you want to stop this job?'} if run.running?
			=#link_to "restart", restart_run_path(@job.id, run.id), {:confirm => 'Are you sure you want to stop this job?'} if run.finished?
			=link_to "re-run", restart_run_path(@job, run), :confirm => 'Re-running a command may overwrite files. Are you sure you want to re-run this command?', :method => :delete if run.finished?
			=link_to "xml", job_run_path(@job, run, :format => 'xml')
			=link_to "delete", job_run_path(@job, run), :confirm => 'Are you sure? This job will continue running but it will be deleted from the pipeline.', :method => :delete
	%span.title.command Command
	.command_string=link_to run.command_string, edit_job_run_path(@job, run), :title => 'Click to edit'
	-if run.stdout and !run.stdout.empty?
		%span.title.output Output
		.stdout
			=run.stdout
	
	-if run.stderr and !run.stderr.empty?
	
		%span.title.error Errors 
		.stderr
			=run.stderr
	=#link_to 'edit', edit_job_run_path(@job, run)
	=#link_to "add command", {:controller => 'runs', :action => 'new', :job_id => @job.id, :waiting_on_run_id => -1, :command_id => 13}, {:class => 'add_command'}
	=form_tag(new_job_run_path(@job), {:method => 'get', :class => 'autosubmit', :style => 'display:inline'}) do |f|
		-# optgroups?
		= hidden_field_tag 'job_id', @job.id
		= hidden_field_tag 'waiting_on_run_id', run.id
		=label_tag 'command_id', 'add dependent command:'
		= select_tag "command_id", options_from_collection_for_select(Command.select("name, id"), "id", "name"), {:include_blank => true}
		= submit_tag 'add'
	
	-unless run.files.empty?
		%br
		- run.files.each do |file|
			-
			=file
			%br
	
	%ul
		-child_runs.each do |child|
			=render :partial => 'jobs/run', :locals => {:run => @runs.find(child.first), :runs => @runs, :job => @job, :child_runs => child.second}

app/views/jobs/edit.html.haml
- title "Edit Job"

= render 'form'

%p
  = link_to "Show", @job
  |
  = link_to "View All", jobs_path

app/views/jobs/index.html.haml
- title "Jobs"

%table#jobs
	%tr
		%th Name
		%th Runs
		%th Age
	- for job in @jobs
		%tr
			%td= link_to job.name, job
			%td
				-job.runs.each_with_index do |r,i|
					= '| ' unless i == 0
					%a{:class => r.torque_status, :href => job_url(job)}
						=r.command.name if r.command and r.command.name
			/ %td= link_to 'Edit', edit_job_path(job)
			%td= time_ago_in_words job.created_at
			%td= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete
			%td= link_to 'Download', job_path(job, :format => 'zip')

%p= link_to "New Job", new_job_path

app/views/jobs/new.html.haml
- title "New Job"

= render 'form'

%p= link_to "Back to List", jobs_path

app/views/jobs/show.html.haml
- title "#{@job.name}"
=link_to 'start', {:action => 'start_job'}, {:class => 'button'} unless @job.running? or @job.finished?
=link_to 'download', job_path(@job, :format => 'zip')
.clear

-if @runs.empty?
        =#link_to "add command", {:controller => 'runs', :action => 'new', :job_id => @job.id, :waiting_on_run_id => -1, :command_id => 13}, {:class => 'add_command'}
        =form_tag(new_job_run_path(@job), {:method => 'get', :class => 'autosubmit'}) do |f|
                -# optgroups?
                = hidden_field_tag 'job_id', @job.id
                =# hidden_field_tag 'waiting_on_run_id', -1
                =label_tag 'command_id', 'add command:'
                = select_tag "command_id", options_from_collection_for_select(Command.select("name, id"), "id", "name"), {:include_blank => true}
                = submit_tag 'add'

-else
        %ul
                - @nested_run_ids.each do |child|
                        =render :partial => 'jobs/run', :locals => {:run => @runs.find(child.first), :runs => @runs, :job => @job, :child_runs => child.second}



%br
%br
%p
        = link_to "Edit Job Name", edit_job_path(@job)
        |
        = link_to "Destroy Job", @job, :confirm => 'Are you sure?', :method => :delete
        |
        = link_to "View All Jobs", jobs_path