config/routes.rb
Pipeline::Application.routes.draw do
  resources :jobs do
    resources :runs
    match 'files' => 'files#index'
    match 'download' => 'jobs#download'
  end
  match 'jobs/:id/start' => 'jobs#start_job', :as => :start_job
  match 'jobs/:job_id/runs/:id/stop' => 'runs#stop', :as => :stop_run
  match 'jobs/:job_id/runs/:id/restart' => 'runs#restart', :as => :restart_run

  resources :commands do
    member do
      match 'download' => 'commands#download'
    end
  end
  

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "users#index"

end

app/models/command.rb
class Command < ActiveRecord::Base
  include XmlHelper
  attr_accessible :alias, :path, :description, :module, :name, :version, :xml_data, :xsd_data, :default_xml_preferences_data, :upload
  
  has_many :runs
  
  before_validation :parse_xml_data
  validates :xml_data, :with_schema => true
  validates :xsd_data, :with_schema => true
  validates :default_xml_preferences_data, :with_schema => true
  
  after_create :create_plugin_directory, :create_documentation
  
  def xml_data=(input_data)
    input_data = input_data.read if input_data.respond_to? :read
    super input_data
  end
  
  def xml
    return nil unless xml_data
    @xml ||= Nokogiri::XML xml_data
  end
  
  def expected_file_args
    args = []
    xml.search("arg").each{|arg|
      if arg[:type] == "filepath" and arg[:flag].nil?
        args << arg
      end
    }
    args
  end
  
  def plugin_directory
    dirname = "#{id}_#{self.alias.gsub(' ','_').underscore}"
    PLUGIN_DIRECTORY_PATH.join(dirname)
  end
  
  def path_directory
    return nil unless path
    File.dirname(path)
  end
    
  # private
  
  def create_plugin_directory
    Dir.mkdir plugin_directory
  end
  
  def create_documentation
    tab = "  "
    
    def h1(s); "## #{s.to_s.upcase}\n\n"; end
    
    name = xml.at('command')[:name]
    alias_name = xml.at('command')[:alias]
    version = xml.at('command')[:version]
    title = alias_name + "(1) -- " + name
    
    output_filename = "doc/#{id}_#{alias_name}.ronn"
    file = File.new(output_filename, 'w')
    #file.chown(0,0)
    file.puts title
    file.puts '='*title.length
    file.puts
    
    file.puts h1(:description)
    file.puts tab + xml.at('command')[:description]
    file.puts
    
    file.puts h1 :options
    xml.search('arg').each{|arg|
      file.puts tab + "* `#{arg[:flag]}`, `#{arg[:name]}` <#{arg[:type]}>:"
      file.print tab + arg[:description]
      file.print " [**#{arg[:default]}**]" if arg[:default]
      file.puts
    }
    file.close
    
    `ronn #{output_filename}`
  end
  
  private
  
  def xs(str)
    "xs:#{str}"
  end
  
  def parse_xml_data
    # assign command attributes
    %w(alias description module name version).each{|attribute|
      self.send(attribute + "=", xml.at("command")[attribute])
      # p xml.at("command")[attribute]
    }
    
    # build xsd
    builder = Nokogiri::XML::Builder.new do |doc|
      doc.send('xs:schema', :'xmlns:xs' => "http://www.w3.org/2001/XMLSchema"){
        doc.send('xs:annotation'){
          doc.send('xs:appinfo', xml.at('command')[:name])
          doc.send('xs:documentation', xml.at('command')[:description], 'xml:lang' => 'en')
        }
        doc.send('xs:element', :name => xml.at('command')[:alias]){
          doc.send('xs:complexType'){
            doc.send('xs:choice', :maxOccurs => "unbounded", :minOccurs => "0"){
              xml.search('arg').each{|arg|
                attrs = {}

                restrictions = [:maxExclusive, :maxInclusive, :minExclusive, :minInclusive, :fractionDigits, :length, :maxLength, :minLength, :pattern, :whiteSpace, :totalDigits, :acceptedValues]
                complex_restrictions = !(arg.keys & restrictions.map(&:to_s)).empty?

                [:name, :default].each{|a|
                  attrs[a] = arg[a] if arg[a]
                }

                type = arg[:type]
                type = 'string' if type == "filepath"
                attrs[:type] = xs(type) if type and !complex_restrictions
                attrs[:nillable] = "true"

                doc.send('xs:element', attrs){
                  if complex_restrictions
                    doc.send('xs:simpleType'){
                      doc.send('xs:restriction', :base => 'xs:' + type){
                        restrictions.each{|a|
                          if a == :acceptedValues and arg[:acceptedValues]
                            arg[:acceptedValues].split(',').map(&:strip).each{|value|
                              doc.send('xs:enumeration', :value => value)
                            }
                          else
                            doc.send(xs(a), :value => arg[a]) if arg[a]
                          end
                        }
                      }
                    }
                  end
                }
              }
            }
          }
        }
      }
    end

    self.xsd_data = builder.to_xml


    # default XML preference file
    builder = Nokogiri::XML::Builder.new do |doc|
      doc.send(xml.at('command')[:alias]){
        doc << "\n"
        xml.search('arg').each{|arg|
          # Nokogiri::XML::Comment.new("test", doc)
          doc << "<!-- (#{arg[:type]}) #{arg[:description]}-->\n"
          default = arg[:default] ? arg[:default] : nil
          default = 'false' if default.nil? && arg[:type].index('boolean')
          
          # for integer parameters with no default value
          # default = "" if !arg[:default] and arg[:type] == "integer"
          
          doc.send(arg[:name], default)
          doc << "\n\n"
        }
      }
    end
    self.default_xml_preferences_data = builder.to_xml
    true
    
  end
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_filter :daemon_running?
  
  def index
    @commands = Command.all
  end

  def show
    @command = Command.find(params[:id])
  end
  
  def download
    @command = Command.find(params[:id])
    file = params[:filename]
    file_name = @command.alias
    t = Tempfile.new("my-temp-filename-#{Time.now}")
    Zip::ZipOutputStream.open(t.path) do |z|
      Dir[Rails.root.join("doc/#{@command.id}_*")].each{|filename|
        title = File.basename(filename).sub("#{@command.id}_", '')
        z.put_next_entry(title)
        z.puts File.open(filename).read.gsub('\n', "\n")
      }
      
      z.put_next_entry(@command.alias + ".xml")
      z.puts @command.xml_data
      z.put_next_entry(@command.alias + ".xsd")
      z.puts @command.xsd_data
      z.put_next_entry(@command.alias + "_defaults.xml")
      z.puts @command.default_xml_preferences_data
    end
    send_data data, :type => 'application/zip', :disposition => 'attachment', :filename => file_name
    t.close
  end

  def new
    @command = Command.new
  end

  def create
    @command = Command.new(params[:command])
    if @command.save
      redirect_to @command, :notice => "Successfully created command."
    else
      render :action => 'new'
    end
  end

  def edit
    @command = Command.find(params[:id])
  end

  def update
    @command = Command.find(params[:id])
    if @command.update_attributes(params[:command])
      redirect_to @command, :notice  => "Successfully updated command."
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @command = Command.find(params[:id])
    @command.destroy
    redirect_to commands_url, :notice => "Successfully destroyed command."
  end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.haml
= form_for @command, :html => {:multipart => true} do |f|
	= f.error_messages
	-#
		%p
			= f.label :alias
			%br
			= f.text_field :alias
		%p
			= f.label :path
			%br
			= f.text_field :path
		%p
			= f.label :description
			%br
			= f.text_area :description
		%p
			= f.label :module
			%br
			= f.text_field :module
		%p
			= f.label :name
			%br
			= f.text_field :name
		%p
			= f.label :version
			%br
			= f.text_field :version
	%p
		= f.label :path, "Absolute path of the command on the server"
		%br
		= f.text_field :path
	%p
		= f.label :xml_data, 'XML Definitions'
		%br
		= f.file_field :xml_data
	%p= f.submit :class => 'submit'

app/views/commands/edit.html.erb
<% title "Edit Command" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @command %> |
  <%= link_to "View All", commands_path %>
</p>

app/views/commands/index.html.haml
= link_to "New Command", new_command_path

%br
%br
%br

-for command in @commands
  %h1= command.name
  =# link_to "Show", command
  = link_to "Edit", edit_command_path(command)
  = link_to "Destroy", command, :confirm => 'Are you sure?', :method => :delete
  %br
  %p
    =command.path
  %p
    / files:
    / -files = ["#{command.alias}.xml", "#{command.alias}.xsd", "#{command.alias}_default_preferences.xml"]
    / -files.each do |file|
    /   = link_to file, :controller => 'commands', :action => 'download', :id => command.id
    =link_to "Download all XML and docs", :controller => 'commands', :action => 'download', :id => command.id

  %p
    =command.description

app/views/commands/new.html.haml
-title "New Command"


%p
	Note: the command's XML file will be validated against
	=link_to "command.xsd", "/command.xsd"

= render 'form'


%p
	= link_to "Back to List", commands_path

app/views/commands/show.html.erb
<% title "Command" %>

<p>
  <strong>Alias:</strong>
  <%= @command.alias %>
</p>
<p>
  <strong>Path:</strong>
  <%= @command.path %>
</p>
<p>
  <strong>Description:</strong>
  <%= @command.description %>
</p>
<p>
  <strong>Module:</strong>
  <%= @command.module %>
</p>
<p>
  <strong>Name:</strong>
  <%= @command.name %>
</p>
<p>
  <strong>Version:</strong>
  <%= @command.version %>
</p>
<p>
  <strong>Xml Binary:</strong>
  <%-# debug @command.xml_data %>
</p>
<p>
  <strong>Xsd Binary:</strong>
  <%-# @command.xsd_data %>
</p>
<p>
  <strong>Default Xml Preferences Binary:</strong>
  <%-# @command.default_xml_preferences_data %>
</p>

<p>
  <%= link_to "Edit", edit_command_path(@command) %> |
  <%= link_to "Destroy", @command, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", commands_path %>
</p>