config/routes.rb
Pipeline::Application.routes.draw do
  resources :jobs do
    resources :runs
    match 'files' => 'files#index'
    match 'download' => 'jobs#download'
  end
  match 'jobs/:id/start' => 'jobs#start_job', :as => :start_job
  match 'jobs/:job_id/runs/:id/stop' => 'runs#stop', :as => :stop_run
  match 'jobs/:job_id/runs/:id/restart' => 'runs#restart', :as => :restart_run

  resources :commands do
    member do
      match 'download' => 'commands#download'
    end
  end
  

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "users#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title
			= yield(:title) || "Untitled"
		%meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
		= stylesheet_link_tag "reset", "application", "jqueryFileTree.css"
		= javascript_include_tag :defaults, 'jquery.zclip.min', 'jquery.tools.min.js', 'jqueryFileTree.js'
		= csrf_meta_tag
		= yield(:head)
	%body
		- flash.each do |name, msg|
			%div{:id => "flash_#{name}", :class => 'flash'}
				%span=msg
		#container
			#user_nav
				=link_to 'commands', commands_url
				|
				=link_to 'jobs', jobs_url
				-#
					-if current_user
						#{current_user.email}
						=link_to 'logout', logout_path
					-else
						= form_tag sessions_path, :id => 'login' do
							= text_field_tag :login, params[:login], :placeholder => 'example@smu.edu'
							= password_field_tag :password, '', :placeholder => 'Password'
							= submit_tag "Sign in/Register", :class => 'submit'
			%h1#header
				%a{:href => root_path}			
					QBRC 
					%em pipeline server
			.clear
			
			%hr

			- if show_title?
				%h1= yield(:title)
			
			= yield
		#footer
			.shadow
			.content
				Copyright 2011 UT Southwestern. All rights reserved.
				-if @daemon_pid
					%span{:style => 'color: green'} Daemon running (pid##{@daemon_pid})
				-else
					%span{:style => 'color: red; font-weight: bold'} DAEMON STOPPED
					Restart daemon with: 
					%br
					sudo #{Rails.root}/lib/daemons/job_monitor_ctl restart
					%br
					Having problems? Try running the ruby file manually and checking for errors in the output:
					%br
					sudo ruby #{Rails.root}/lib/daemons/job_monitor.rb